<template>
  <div class="wrapper">
    <ul class="content">
      <li>categorylist1</li>
      <li>categorylist2</li>
      <li>categorylist3</li>
      <li>categorylist4</li>
      <li>categorylist5</li>
      <li>categorylist6</li>
      <li>categorylist7</li>
      <li>categorylist8</li>
      <li>categorylist9</li>
      <li>categorylist10</li>
      <li>categorylist11</li>
      <li>categorylist12</li>
      <li>categorylist13</li>
      <li>categorylist14</li>
      <li>categorylist15</li>
      <li>categorylist16</li>
      <li>categorylist17</li>
      <li>categorylist18</li>
      <li>categorylist19</li>
      <li>categorylist20</li>
      <li>categorylist21</li>
      <li>categorylist22</li>
      <li>categorylist23</li>
      <li>categorylist24</li>
      <li>categorylist25</li>
      <li>categorylist26</li>
      <li>categorylist27</li>
      <li>categorylist28</li>
      <li>categorylist29</li>
      <li>categorylist30</li>
      <li>categorylist31</li>
      <li>categorylist32</li>
      <li>categorylist33</li>
      <li>categorylist34</li>
      <li>categorylist35</li>
      <li>categorylist36</li>
      <li>categorylist37</li>
      <li>categorylist38</li>
      <li>categorylist39</li>
      <li>categorylist40</li>
      <li>categorylist41</li>
      <li>categorylist42</li>
      <li>categorylist43</li>
      <li>categorylist44</li>
      <li>categorylist45</li>
      <li>categorylist46</li>
      <li>categorylist47</li>
      <li>categorylist48</li>
      <li>categorylist49</li>
      <li>categorylist50</li>
      <li>categorylist51</li>
      <li>categorylist52</li>
      <li>categorylist53</li>
      <li>categorylist54</li>
      <li>categorylist55</li>
      <li>categorylist56</li>
      <li>categorylist57</li>
      <li>categorylist58</li>
      <li>categorylist59</li>
      <li>categorylist60</li>
      <li>categorylist61</li>
      <li>categorylist62</li>
      <li>categorylist63</li>
      <li>categorylist64</li>
      <li>categorylist65</li>
      <li>categorylist66</li>
      <li>categorylist67</li>
      <li>categorylist68</li>
      <li>categorylist69</li>
      <li>categorylist70</li>
      <li>categorylist71</li>
      <li>categorylist72</li>
      <li>categorylist73</li>
      <li>categorylist74</li>
      <li>categorylist75</li>
      <li>categorylist76</li>
      <li>categorylist77</li>
      <li>categorylist78</li>
      <li>categorylist79</li>
      <li>categorylist80</li>
      <li>categorylist81</li>
      <li>categorylist82</li>
      <li>categorylist83</li>
      <li>categorylist84</li>
      <li>categorylist85</li>
      <li>categorylist86</li>
      <li>categorylist87</li>
      <li>categorylist88</li>
      <li>categorylist89</li>
      <li>categorylist90</li>
      <li>categorylist91</li>
      <li>categorylist92</li>
      <li>categorylist93</li>
      <li>categorylist94</li>
      <li>categorylist95</li>
      <li>categorylist96</li>
      <li>categorylist97</li>
      <li>categorylist98</li>
      <li>categorylist99</li>
      <li>categorylist100</li>
      <li>categorylist101</li>
      <li>categorylist102</li>
      <li>categorylist103</li>
      <li>categorylist104</li>
      <li>categorylist105</li>
      <li>categorylist106</li>
      <li>categorylist107</li>
      <li>categorylist108</li>
      <li>categorylist109</li>
      <li>categorylist110</li>
      <li>categorylist111</li>
      <li>categorylist112</li>
      <li>categorylist113</li>
      <li>categorylist114</li>
      <li>categorylist115</li>
      <li>categorylist116</li>
      <li>categorylist117</li>
      <li>categorylist118</li>
      <li>categorylist119</li>
      <li>categorylist120</li>
      <li>categorylist121</li>
      <li>categorylist122</li>
      <li>categorylist123</li>
      <li>categorylist124</li>
      <li>categorylist125</li>
      <li>categorylist126</li>
      <li>categorylist127</li>
      <li>categorylist128</li>
      <li>categorylist129</li>
      <li>categorylist130</li>
      <li>categorylist131</li>
      <li>categorylist132</li>
      <li>categorylist133</li>
      <li>categorylist134</li>
      <li>categorylist135</li>
      <li>categorylist136</li>
      <li>categorylist137</li>
      <li>categorylist138</li>
      <li>categorylist139</li>
      <li>categorylist140</li>
      <li>categorylist141</li>
      <li>categorylist142</li>
      <li>categorylist143</li>
      <li>categorylist144</li>
      <li>categorylist145</li>
      <li>categorylist146</li>
      <li>categorylist147</li>
      <li>categorylist148</li>
      <li>categorylist149</li>
      <li>categorylist150</li>
      <li>categorylist151</li>
      <li>categorylist152</li>
      <li>categorylist153</li>
      <li>categorylist154</li>
      <li>categorylist155</li>
      <li>categorylist156</li>
      <li>categorylist157</li>
      <li>categorylist158</li>
      <li>categorylist159</li>
      <li>categorylist160</li>
      <li>categorylist161</li>
      <li>categorylist162</li>
      <li>categorylist163</li>
      <li>categorylist164</li>
      <li>categorylist165</li>
      <li>categorylist166</li>
      <li>categorylist167</li>
      <li>categorylist168</li>
      <li>categorylist169</li>
      <li>categorylist170</li>
      <li>categorylist171</li>
      <li>categorylist172</li>
      <li>categorylist173</li>
      <li>categorylist174</li>
      <li>categorylist175</li>
      <li>categorylist176</li>
      <li>categorylist177</li>
      <li>categorylist178</li>
      <li>categorylist179</li>
      <li>categorylist180</li>
      <li>categorylist181</li>
      <li>categorylist182</li>
      <li>categorylist183</li>
      <li>categorylist184</li>
      <li>categorylist185</li>
      <li>categorylist186</li>
      <li>categorylist187</li>
      <li>categorylist188</li>
      <li>categorylist189</li>
      <li>categorylist190</li>
      <li>categorylist191</li>
      <li>categorylist192</li>
      <li>categorylist193</li>
      <li>categorylist194</li>
      <li>categorylist195</li>
      <li>categorylist196</li>
      <li>categorylist197</li>
      <li>categorylist198</li>
      <li>categorylist199</li>
      <li>categorylist200</li>
      <li>categorylist201</li>
      <li>categorylist202</li>
      <li>categorylist203</li>
      <li>categorylist204</li>
      <li>categorylist205</li>
      <li>categorylist206</li>
      <li>categorylist207</li>
      <li>categorylist208</li>
      <li>categorylist209</li>
      <li>categorylist210</li>
      <li>categorylist211</li>
      <li>categorylist212</li>
      <li>categorylist213</li>
      <li>categorylist214</li>
      <li>categorylist215</li>
      <li>categorylist216</li>
      <li>categorylist217</li>
      <li>categorylist218</li>
      <li>categorylist219</li>
      <li>categorylist220</li>
      <li>categorylist221</li>
      <li>categorylist222</li>
      <li>categorylist223</li>
      <li>categorylist224</li>
      <li>categorylist225</li>
      <li>categorylist226</li>
      <li>categorylist227</li>
      <li>categorylist228</li>
      <li>categorylist229</li>
      <li>categorylist230</li>
      <li>categorylist231</li>
      <li>categorylist232</li>
      <li>categorylist233</li>
      <li>categorylist234</li>
      <li>categorylist235</li>
      <li>categorylist236</li>
      <li>categorylist237</li>
      <li>categorylist238</li>
      <li>categorylist239</li>
      <li>categorylist240</li>
      <li>categorylist241</li>
      <li>categorylist242</li>
      <li>categorylist243</li>
      <li>categorylist244</li>
      <li>categorylist245</li>
      <li>categorylist246</li>
      <li>categorylist247</li>
      <li>categorylist248</li>
      <li>categorylist249</li>
      <li>categorylist250</li>
      <li>categorylist251</li>
      <li>categorylist252</li>
      <li>categorylist253</li>
      <li>categorylist254</li>
      <li>categorylist255</li>
      <li>categorylist256</li>
      <li>categorylist257</li>
      <li>categorylist258</li>
      <li>categorylist259</li>
      <li>categorylist260</li>
      <li>categorylist261</li>
      <li>categorylist262</li>
      <li>categorylist263</li>
      <li>categorylist264</li>
      <li>categorylist265</li>
      <li>categorylist266</li>
      <li>categorylist267</li>
      <li>categorylist268</li>
      <li>categorylist269</li>
      <li>categorylist270</li>
      <li>categorylist271</li>
      <li>categorylist272</li>
      <li>categorylist273</li>
      <li>categorylist274</li>
      <li>categorylist275</li>
      <li>categorylist276</li>
      <li>categorylist277</li>
      <li>categorylist278</li>
      <li>categorylist279</li>
      <li>categorylist280</li>
      <li>categorylist281</li>
      <li>categorylist282</li>
      <li>categorylist283</li>
      <li>categorylist284</li>
      <li>categorylist285</li>
      <li>categorylist286</li>
      <li>categorylist287</li>
      <li>categorylist288</li>
      <li>categorylist289</li>
      <li>categorylist290</li>
      <li>categorylist291</li>
      <li>categorylist292</li>
      <li>categorylist293</li>
      <li>categorylist294</li>
      <li>categorylist295</li>
      <li>categorylist296</li>
      <li>categorylist297</li>
      <li>categorylist298</li>
      <li>categorylist299</li>
      <li>categorylist300</li>
      <li>categorylist301</li>
      <li>categorylist302</li>
      <li>categorylist303</li>
      <li>categorylist304</li>
      <li>categorylist305</li>
      <li>categorylist306</li>
      <li>categorylist307</li>
      <li>categorylist308</li>
      <li>categorylist309</li>
      <li>categorylist310</li>
      <li>categorylist311</li>
      <li>categorylist312</li>
      <li>categorylist313</li>
      <li>categorylist314</li>
      <li>categorylist315</li>
      <li>categorylist316</li>
      <li>categorylist317</li>
      <li>categorylist318</li>
      <li>categorylist319</li>
      <li>categorylist320</li>
      <li>categorylist321</li>
      <li>categorylist322</li>
      <li>categorylist323</li>
      <li>categorylist324</li>
      <li>categorylist325</li>
      <li>categorylist326</li>
      <li>categorylist327</li>
      <li>categorylist328</li>
      <li>categorylist329</li>
      <li>categorylist330</li>
      <li>categorylist331</li>
      <li>categorylist332</li>
      <li>categorylist333</li>
      <li>categorylist334</li>
      <li>categorylist335</li>
      <li>categorylist336</li>
      <li>categorylist337</li>
      <li>categorylist338</li>
      <li>categorylist339</li>
      <li>categorylist340</li>
      <li>categorylist341</li>
      <li>categorylist342</li>
      <li>categorylist343</li>
      <li>categorylist344</li>
      <li>categorylist345</li>
      <li>categorylist346</li>
      <li>categorylist347</li>
      <li>categorylist348</li>
      <li>categorylist349</li>
      <li>categorylist350</li>
      <li>categorylist351</li>
      <li>categorylist352</li>
      <li>categorylist353</li>
      <li>categorylist354</li>
      <li>categorylist355</li>
      <li>categorylist356</li>
      <li>categorylist357</li>
      <li>categorylist358</li>
      <li>categorylist359</li>
      <li>categorylist360</li>
      <li>categorylist361</li>
      <li>categorylist362</li>
      <li>categorylist363</li>
      <li>categorylist364</li>
      <li>categorylist365</li>
      <li>categorylist366</li>
      <li>categorylist367</li>
      <li>categorylist368</li>
      <li>categorylist369</li>
      <li>categorylist370</li>
      <li>categorylist371</li>
      <li>categorylist372</li>
      <li>categorylist373</li>
      <li>categorylist374</li>
      <li>categorylist375</li>
      <li>categorylist376</li>
      <li>categorylist377</li>
      <li>categorylist378</li>
      <li>categorylist379</li>
      <li>categorylist380</li>
      <li>categorylist381</li>
      <li>categorylist382</li>
      <li>categorylist383</li>
      <li>categorylist384</li>
      <li>categorylist385</li>
      <li>categorylist386</li>
      <li>categorylist387</li>
      <li>categorylist388</li>
      <li>categorylist389</li>
      <li>categorylist390</li>
      <li>categorylist391</li>
      <li>categorylist392</li>
      <li>categorylist393</li>
      <li>categorylist394</li>
      <li>categorylist395</li>
      <li>categorylist396</li>
      <li>categorylist397</li>
      <li>categorylist398</li>
      <li>categorylist399</li>
      <li>categorylist400</li>
      <li>categorylist401</li>
      <li>categorylist402</li>
      <li>categorylist403</li>
      <li>categorylist404</li>
      <li>categorylist405</li>
      <li>categorylist406</li>
      <li>categorylist407</li>
      <li>categorylist408</li>
      <li>categorylist409</li>
      <li>categorylist410</li>
      <li>categorylist411</li>
      <li>categorylist412</li>
      <li>categorylist413</li>
      <li>categorylist414</li>
      <li>categorylist415</li>
      <li>categorylist416</li>
      <li>categorylist417</li>
      <li>categorylist418</li>
      <li>categorylist419</li>
      <li>categorylist420</li>
      <li>categorylist421</li>
      <li>categorylist422</li>
      <li>categorylist423</li>
      <li>categorylist424</li>
      <li>categorylist425</li>
      <li>categorylist426</li>
      <li>categorylist427</li>
      <li>categorylist428</li>
      <li>categorylist429</li>
      <li>categorylist430</li>
      <li>categorylist431</li>
      <li>categorylist432</li>
      <li>categorylist433</li>
      <li>categorylist434</li>
      <li>categorylist435</li>
      <li>categorylist436</li>
      <li>categorylist437</li>
      <li>categorylist438</li>
      <li>categorylist439</li>
      <li>categorylist440</li>
      <li>categorylist441</li>
      <li>categorylist442</li>
      <li>categorylist443</li>
      <li>categorylist444</li>
      <li>categorylist445</li>
      <li>categorylist446</li>
      <li>categorylist447</li>
      <li>categorylist448</li>
      <li>categorylist449</li>
      <li>categorylist450</li>
      <li>categorylist451</li>
      <li>categorylist452</li>
      <li>categorylist453</li>
      <li>categorylist454</li>
      <li>categorylist455</li>
      <li>categorylist456</li>
      <li>categorylist457</li>
      <li>categorylist458</li>
      <li>categorylist459</li>
      <li>categorylist460</li>
      <li>categorylist461</li>
      <li>categorylist462</li>
      <li>categorylist463</li>
      <li>categorylist464</li>
      <li>categorylist465</li>
      <li>categorylist466</li>
      <li>categorylist467</li>
      <li>categorylist468</li>
      <li>categorylist469</li>
      <li>categorylist470</li>
      <li>categorylist471</li>
      <li>categorylist472</li>
      <li>categorylist473</li>
      <li>categorylist474</li>
      <li>categorylist475</li>
      <li>categorylist476</li>
      <li>categorylist477</li>
      <li>categorylist478</li>
      <li>categorylist479</li>
      <li>categorylist480</li>
      <li>categorylist481</li>
      <li>categorylist482</li>
      <li>categorylist483</li>
      <li>categorylist484</li>
      <li>categorylist485</li>
      <li>categorylist486</li>
      <li>categorylist487</li>
      <li>categorylist488</li>
      <li>categorylist489</li>
      <li>categorylist490</li>
      <li>categorylist491</li>
      <li>categorylist492</li>
      <li>categorylist493</li>
      <li>categorylist494</li>
      <li>categorylist495</li>
      <li>categorylist496</li>
      <li>categorylist497</li>
      <li>categorylist498</li>
      <li>categorylist499</li>
      <li>categorylist500</li>
    </ul>
  </div>
</template>

<script>
import BScroll from '@better-scroll/core'
export default {
  name: "Category",
  data() {
    return {
      scroll: null
    }
  },

  mounted() {
    this.scroll = new BScroll('.wrapper',{
      
    })
  }
}
</script>

<style>
  .wrapper {
    height: 250px;
    background-color: darksalmon;
    overflow: hidden;
  }
</style>