<template>
  <div class="cart-list">
    <div>
      <cart-list-item 
      v-for="(item, index) in cartList" :key="index"
      :itemInfo="item"
      ></cart-list-item>
    </div>
    <ul>
      <li>lsit1</li>
      <li>lsit2</li>
      <li>lsit3</li>
      <li>lsit4</li>
      <li>lsit5</li>
      <li>lsit6</li>
      <li>lsit7</li>
      <li>lsit8</li>
      <li>lsit9</li>
      <li>lsit10</li>
      <li>lsit11</li>
      <li>lsit12</li>
      <li>lsit13</li>
      <li>lsit14</li>
      <li>lsit15</li>
      <li>lsit16</li>
      <li>lsit17</li>
      <li>lsit18</li>
      <li>lsit19</li>
      <li>lsit20</li>
      <li>lsit21</li>
      <li>lsit22</li>
      <li>lsit23</li>
      <li>lsit24</li>
      <li>lsit25</li>
      <li>lsit26</li>
      <li>lsit27</li>
      <li>lsit28</li>
      <li>lsit29</li>
      <li>lsit30</li>
      <li>lsit31</li>
      <li>lsit32</li>
      <li>lsit33</li>
      <li>lsit34</li>
      <li>lsit35</li>
      <li>lsit36</li>
      <li>lsit37</li>
      <li>lsit38</li>
      <li>lsit39</li>
      <li>lsit40</li>
      <li>lsit41</li>
      <li>lsit42</li>
      <li>lsit43</li>
      <li>lsit44</li>
      <li>lsit45</li>
      <li>lsit46</li>
      <li>lsit47</li>
      <li>lsit48</li>
      <li>lsit49</li>
      <li>lsit50</li>
      <li>lsit51</li>
      <li>lsit52</li>
      <li>lsit53</li>
      <li>lsit54</li>
      <li>lsit55</li>
      <li>lsit56</li>
      <li>lsit57</li>
      <li>lsit58</li>
      <li>lsit59</li>
      <li>lsit60</li>
      <li>lsit61</li>
      <li>lsit62</li>
      <li>lsit63</li>
      <li>lsit64</li>
      <li>lsit65</li>
      <li>lsit66</li>
      <li>lsit67</li>
      <li>lsit68</li>
      <li>lsit69</li>
      <li>lsit70</li>
      <li>lsit71</li>
      <li>lsit72</li>
      <li>lsit73</li>
      <li>lsit74</li>
      <li>lsit75</li>
      <li>lsit76</li>
      <li>lsit77</li>
      <li>lsit78</li>
      <li>lsit79</li>
      <li>lsit80</li>
      <li>lsit81</li>
      <li>lsit82</li>
      <li>lsit83</li>
      <li>lsit84</li>
      <li>lsit85</li>
      <li>lsit86</li>
      <li>lsit87</li>
      <li>lsit88</li>
      <li>lsit89</li>
      <li>lsit90</li>
      <li>lsit91</li>
      <li>lsit92</li>
      <li>lsit93</li>
      <li>lsit94</li>
      <li>lsit95</li>
      <li>lsit96</li>
      <li>lsit97</li>
      <li>lsit98</li>
      <li>lsit99</li>
      <li>lsit100</li>
      <li>lsit101</li>
      <li>lsit102</li>
      <li>lsit103</li>
      <li>lsit104</li>
      <li>lsit105</li>
      <li>lsit106</li>
      <li>lsit107</li>
      <li>lsit108</li>
      <li>lsit109</li>
      <li>lsit110</li>
      <li>lsit111</li>
      <li>lsit112</li>
      <li>lsit113</li>
      <li>lsit114</li>
      <li>lsit115</li>
      <li>lsit116</li>
      <li>lsit117</li>
      <li>lsit118</li>
      <li>lsit119</li>
      <li>lsit120</li>
      <li>lsit121</li>
      <li>lsit122</li>
      <li>lsit123</li>
      <li>lsit124</li>
      <li>lsit125</li>
      <li>lsit126</li>
      <li>lsit127</li>
      <li>lsit128</li>
      <li>lsit129</li>
      <li>lsit130</li>
      <li>lsit131</li>
      <li>lsit132</li>
      <li>lsit133</li>
      <li>lsit134</li>
      <li>lsit135</li>
      <li>lsit136</li>
      <li>lsit137</li>
      <li>lsit138</li>
      <li>lsit139</li>
      <li>lsit140</li>
      <li>lsit141</li>
      <li>lsit142</li>
      <li>lsit143</li>
      <li>lsit144</li>
      <li>lsit145</li>
      <li>lsit146</li>
      <li>lsit147</li>
      <li>lsit148</li>
      <li>lsit149</li>
      <li>lsit150</li>
      <li>lsit151</li>
      <li>lsit152</li>
      <li>lsit153</li>
      <li>lsit154</li>
      <li>lsit155</li>
      <li>lsit156</li>
      <li>lsit157</li>
      <li>lsit158</li>
      <li>lsit159</li>
      <li>lsit160</li>
      <li>lsit161</li>
      <li>lsit162</li>
      <li>lsit163</li>
      <li>lsit164</li>
      <li>lsit165</li>
      <li>lsit166</li>
      <li>lsit167</li>
      <li>lsit168</li>
      <li>lsit169</li>
      <li>lsit170</li>
      <li>lsit171</li>
      <li>lsit172</li>
      <li>lsit173</li>
      <li>lsit174</li>
      <li>lsit175</li>
      <li>lsit176</li>
      <li>lsit177</li>
      <li>lsit178</li>
      <li>lsit179</li>
      <li>lsit180</li>
      <li>lsit181</li>
      <li>lsit182</li>
      <li>lsit183</li>
      <li>lsit184</li>
      <li>lsit185</li>
      <li>lsit186</li>
      <li>lsit187</li>
      <li>lsit188</li>
      <li>lsit189</li>
      <li>lsit190</li>
      <li>lsit191</li>
      <li>lsit192</li>
      <li>lsit193</li>
      <li>lsit194</li>
      <li>lsit195</li>
      <li>lsit196</li>
      <li>lsit197</li>
      <li>lsit198</li>
      <li>lsit199</li>
      <li>lsit200</li>
    </ul>
  </div>
</template>

<script>
import { mapGetters } from "vuex";
import CartListItem from "./CartListItem.vue";

export default {
  components: { CartListItem },
  name: "CartList",
  computed: {
    ...mapGetters(["cartList"]),
  },
};
</script>

<style scoped>
</style>